# Default configuration for Keystore Manager
keystore:
  default_path: "keystore"
  default_key_size: 2048
  secure_delete: true
  password_protected_keys: true

certificates:
  default_path: "certificates"
  default_validity_days: 365
  default_key_size: 2048
  default_country: "US"
  default_organization: "Keystore Practice"

security:
  audit_logging: true
  audit_log_file: "security_audit.log"
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_digits: true
    require_special: true
  
  encryption:
    min_key_size: 2048
    preferred_algorithms:
      - "AES-256-GCM"
      - "RSA-2048"
      - "RSA-4096"
    hash_functions:
      - "SHA-256"
      - "SHA-384"
      - "SHA-512"

file_permissions:
  private_keys: "0600"
  public_keys: "0644"
  certificates: "0644"
  keystore_directory: "0700"
  certificate_directory: "0755"

compliance:
  retain_audit_logs_days: 90
  require_key_rotation_days: 365
  require_certificate_validation: true